### ISSUE TITLE
Urgent Symantec & 41st Issue Rollup

### ISSUE THREAD

**Issue by bowrocker** [basho/riak_repl#381]
- [x] Heartbeat/RTT calc issue: https://github.com/basho/riak_repl/issues/368
- [x] Overload protection issue: https://github.com/basho/riak_repl/issues/359
- [x] Heartbeat config typo (backport from 1.4 to 1.3): https://github.com/basho/riak_repl/issues/374
#### PRs for 1.3
- [x] Heartbeat/RTT: https://github.com/basho/riak_repl/pull/379
- [x] Overload protection: https://github.com/basho/riak_repl/pull/378
- [x] Heartbeat config typo: https://github.com/basho/riak_repl/pull/375
- [x] Drop bad data from the backend: https://github.com/basho/riak_repl/pull/380 (Tapjoy)
#### PRs for 1.4.1
- [x] Heartbeat/RTT: https://github.com/basho/riak_repl/pull/382
- [x] Overload protection: https://github.com/basho/riak_repl/pull/377
- [x] Heartbeat config typo: None, already there
- [x] https://github.com/basho/riak_repl/pull/380 ported to 1.4

**Comment by michellep-basho** [comment]
+1 for 41st (from me and Alex M). thank you

**Comment by bookshelfdave** [comment]
these are for 1.4 only?

**Comment by michellep-basho** [comment]
41st needs the fixes as a patch for 1.3.2 (and later rolled into 1.3.3)

Per Alex M +1 for Symantec.

**Comment by alexmoore** [comment]
41st needs these two, to run on top of the 1.3.2+/1.3.3 patchs that we've sent them.
- Heartbeat/RTT calc issue: #368 
- Heartbeat config typo (backport from 1.4 to 1.3): #374 

Symantec needs the "Overload protection issue: #359", to run on top of the 1.4.1+ patches we've sent them.
Hopefully it will fix their RT Repl OOM issue.

**Comment by alexmoore** [comment]
Previous 1.3.2 patches sent to 41st parameter:  https://help.basho.com/entries/21821274-1-4-riak-repl-Backported-Fixes-to-1-3-

Previous 1.4.1 patches sent to Symantec: https://help.basho.com/entries/21823664-Prevent-RT-Overload-Patch

Should match the beam's that @metadave has listed here: https://gist.github.com/metadave/9b20b62ae60a36ad79e6.

**Comment by michellep-basho** [comment]
Adding that #359 is needed by OpenX.

Update: Per Matt Davis of OpenX their preference is to upgrade to 1.4.2 instead of 1.3.3.

**Comment by lordnull** [comment]
Updated checkbox for #380 since that's been merged. This means everything is checked. I suggest we close this issue. I haven't yet as there are many participants, allowing a chance to state a case for leaving this open.
