### ISSUE TITLE
Cluster connectivity meta-issue

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#462]
collecting cluster_mgr, connection_mgr and service_mgr issues together into one ticket to track progress.

**Comment by bookshelfdave** [comment]
- [ ] [share the realtime put pool between rtsinks](https://github.com/basho/riak_repl/issues/254)
- [ ] [Truncated cluster names](https://github.com/basho/riak_repl/issues/338)
- [ ] [Improve error messages for cluster connection command line](https://github.com/basho/riak_repl/issues/347)
- [x] [Write a riak_test for crashing the cluster manager and confirm restart with good funs](https://github.com/basho/riak_repl/issues/349)
- [ ] [Cluster disconnect should disconnect all connections to that cluster ](https://github.com/basho/riak_repl/issues/354)
- [ ] [Clearer log message for invalid ip for cluster manager when Riak starts](https://github.com/basho/riak_repl/issues/394)
- [ ] [riak_repl2_leader needs to gracefully restart](https://github.com/basho/riak_repl/issues/427)
  - registration funs etc
- [ ] [Replace registered 'locator' functions with passed-in functions for connection manager](https://github.com/basho/riak_repl/issues/431)
- [x] [Node added to cluster with realtime replication enabled and started does not connect to sink](https://github.com/basho/riak_repl/issues/449)
- [ ] [Sources not connecting to sinks in set of clusters using ring topology and cascading replication](https://github.com/basho/riak_repl/issues/452)
- [ ] [leader notify fun and leader query are served from two different sources](https://github.com/basho/riak_repl/issues/459)
- [ ] [Joining a node causes all repl connections to disconnect](https://github.com/basho/riak_repl/issues/460)
- [x] [Move tcp-mon, connection and service manager supervisors from replication to core](https://github.com/basho/riak_repl/pull/398)
- [x] [Reregister cluster name locator.](https://github.com/basho/riak_repl/pull/430)

**Comment by cmeiklejohn** [comment]
I'm assigning myself to this one.  Challenge accepted.

**Comment by bsparrow435** [comment]
I think "Joining a node causes all repl connections to disconnect" is solved with the work @cmeiklejohn did for "Node added to cluster with realtime replication enabled and started does not connect to sink"

**Comment by bookshelfdave** [comment]
Cool, can you log the PR under that item in the list?

**Comment by cmeiklejohn** [comment]
I'm hoping it's also the solution to "Sources not connecting to sinks in set of clusters using ring topology and cascading replication" as well.

**Comment by cmeiklejohn** [comment]
@bsparrow435 Do you have time today to verify these fixes?  I can provide any support you may need.

**Comment by bsparrow435** [comment]
Yes. Which branch/commit should I be testing against?

**Comment by cmeiklejohn** [comment]
1.4, dogg.

**Comment by cmeiklejohn** [comment]
For 2.0, we need to ensure the following PRs get merged:

repl:
https://github.com/basho/riak_repl/pull/469
https://github.com/basho/riak_repl/pull/468

core:
https://github.com/basho/riak_core/pull/473

**Comment by cmeiklejohn** [comment]
Closing in favor of the original issues which can be triaged accordingly.
